apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-world
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: bar-world
          image: hello
          ports:
            - containerPort: 8080
              protocol: TCP
